{% set name = "plucky" %}
{% set version = "0.4.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/plucky-{{ version }}.tar.gz
  sha256: 5bc75d43ae6b40f1b7ba42000b37e4934fa6bd2d6a6cd4e47461f803a404c194

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - plucky
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/randomir/plucky
  summary: Plucking (deep) keys/paths safely from python collections has never been easier.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - BastianZim
